# Generated by Django 4.2.6 on 2023-10-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_adsattributevalue_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='distict',
            new_name='district',
        ),
        migrations.AlterField(
            model_name='ads',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='ads.subcategory'),
        ),
    ]
