# Generated by Django 4.2.6 on 2023-10-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_distict_ads_district_alter_ads_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adsattributevalue',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='ads.ads'),
        ),
        migrations.AlterField(
            model_name='adsattributevalueoption',
            name='ads_attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_options', to='ads.adsattributevalue'),
        ),
    ]
